title: gaussian37
description: # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: ''
url: "https://gaussian37.github.io"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: JINSOL KIM # add your name
author-img: My/me.jpg # add your photo
about-author: Computer Vision for Autonomous Driving
social-twitter: gaussian37 # add your Twitter handle
social-facebook: jinsolkima # add your Facebook handle
social-github: gaussian37 # add your Github handle
social-linkedin: jinsolkima # add your Linkedin handle
social-email: jinsolkima@gmail.com # add your Email address

# Disqus
discus-identifier: gaussian37 # add your discus identifier

# Tracker
analytics: Google Analytics

# Build Settings
markdown: kramdown
kramdown:
  math_engine: nil
maruku:
  use_tex: false


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
