title: gaussian37' Data Science
description: > # this means to ignore newlines until "baseurl:"
  Hello and Welcome gaussian37's Data Science blog.
permalink: ':title/'
baseurl: ''  # the subpath of your site, e.g. /blog
url: "https://gaussian37.github.io/"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: KIM JINSOL # add your name
author-img: kjsandkjs.jpg # add your photo
about-author: gaussian37's Data Science
social-twitter: gaussian37 # add your Twitter handle
social-facebook: gaussian37 # add your Facebook handle
social-github: gaussian37 # add your Github handle
social-linkedin: gaussian37 # add your Linkedin handle
social-email: gaussian1137@gmail.com # add your Email address

# Disqus
discus-identifier: gaussian37 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 15
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
